apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-workout

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-workout
  
  template:
    metadata:
      labels:
        app: my-workout
    spec:
      containers:
        - name: my-workout-site
          image: mariospapaz/my-workout:1.0
          container_name: website
          depends_on:
            - database
          ports:
            - 80:8080

        - name: api 
          image: mariospapaz/api-workout:1.0
          container_name: api
          depends_on: 
            - database
          ports:
            8080:8080

        - name: database
          image: mongo:5.0
          hostname: bibi
          container_name: bibi-mongo
          restart: on-failure
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
