apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/my-workout: "true"
    io.kompose.service: mongo
  name: mongo
spec:
  containers:
    - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
      image: mongo:5.0
      name: bibi-mongo
      resources: {}
  hostname: bibi
  restartPolicy: OnFailure
status: {}
