apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../visitors.yaml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: my-workout
  name: my-workout
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: my-workout
status:
  loadBalancer: {}
