apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: my-workout
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/my-workout: "true"
  podSelector:
    matchLabels:
      io.kompose.network/my-workout: "true"
