name: Azure Deployment

env:
  resourceGroup: 'test'
  kubernetesVersion: '1.22.6'
  name: 'my-workout-cluster'
  

on:
  pull_request:
    branches: [ "main" ]
    
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
              
      - name: Kubernetes Set Context
        uses: Azure/aks-set-context@v3
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: test
          cluster-name: my-workout-cluster
          
      
      - name: Create secret in Kubernetes cluster
        uses: Azure/k8s-create-secret@v3.0
        with:
          container-registry-url: https://index.docker.io/v1/
          container-registry-username: '${{secrets.USERNAME}}'
          container-registry-password: '${{secrets.PASSWORD}}'
          secret-type: docker-registry
          secret-name: docker-image-pull-secret
          
          
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          manifests:
              kube_deployment.yml
              service.yml
              
          images: |
            'mariospapaz/my-workout:1.0'
            'mariospapaz/api-workout:1.0'
            'mongo:5.0'
          
          imagepullsecrets: docker-image-pull-secret
          action: deploy
              
            
