name: Azure Deployment

env:
  resourceGroup: 'test'
  kubernetesVersion: '1.22.6'
  name: 'my-workout-cluster'
  

on:
  pull_request:
    branches: [ "main" ]
    
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2.4.2
  
      - name: Azure Login
        uses: Azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
              
      - name: Kubernetes Set Context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: my-workout-resource
          cluster-name: my-workout-cluster
        
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          images: |
            mariospapaz/my-workout:1.0
            mariospapaz/api-workout:1.0
            mongo:5.0
            
          manifests: |
              ./.github/mongo-pod.yaml
              ./.github/my-workout-api-pod.yaml
              ./.github/my-workout-api-service.yaml
              ./.github/my-workout-networkpolicy.yaml
              ./.github/my-workout-pod.yaml 
              ./.github/my-workout-service.yaml
          
          imagepullsecrets: docker-image-pull-secret
          action: deploy
              
            
